### ISSUE TITLE
binding function causes VS2015 compiler crash

### ISSUE THREAD

**Issue by THE-FYP** [ThePhD/sol2#147]
internal error occurs in compiler when you try to compile the code below.
it only happens if a function returns a tuple with four floats in a row and only with enabled optimization (/O1, /O2 or /Ox) + enabled inline function expansion (/Ob1 or /Ob2). other optimization parameters and floating point model doesn't affect this.

```cpp
std::tuple<float, float, float, float> func()
{
  return std::make_tuple(1.0f, 2.0f, 3.0f, 4.0f);
}

int main()
{
  sol::state lua;
  lua.set_function("func", func);
  return 0;
}
```
error log:
```
1>d:\dev\sources\sol-luajit\sol-luajit\main.cpp(117): fatal error C1001: An internal error has occurred in the compiler.
1>  (compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 255)
1>   To work around this problem, try simplifying or changing the program near the locations listed above.
1>  Please choose the Technical Support command on the Visual C++
1>   Help menu, or open the Technical Support help file for more information
1>    CL!CloseTypeServerPDB()+0x22225
```

**Comment by nabijaczleweli** [comment]
ICEing on the cake.

**Comment by ThePhD** [comment]
This is fixed in some VS 2015 update between {Your Current Version} and the latest Visual Studio 2015 Update 4.

That is, it compiles cleanly for me with no errors in any version on any level of optimization (I tested Ox, O1, O2 with Ob1 / Ob2).

There's nothing I can do to code around VC++ being bad. Hopefully upgrading is of no trouble.

**Comment by THE-FYP** [comment]
there is no Update 4 for VS 2015 and i use latest version as i know (14.0.25424.00 Update 3).
maybe another compilation parameters affect on this...

**Comment by ThePhD** [comment]
Oops. Update 3, but the latest one.

Either way, No combination of optimization flags triggers the error for me. In the error you posted, it says "main.cpp  (117)": the explan you posted isn't 117 lines long. Is there something else you're not posting that goes with that bit of code?

**Comment by THE-FYP** [comment]
i did clear project and restore all compiler parameters to default.
so with code below it still happening
```cpp
#include <iostream>
#include <sol.hpp>

std::tuple<float, float, float, float> func()
{
	return std::make_tuple(1.0f, 2.0f, 3.0f, 4.0f);
}

int main()
{
	sol::state lua;
	lua.set_function("func", func);
	return 0;
}
```
next, following from the function 'sol::state_view::set_function' deeper and commenting line by line i have found that line `detail::forward_get<I * 2 + 1>(pairs),` (95 in file 'table_core.hpp') causes that error, specifically this: `<I * 2 + 1>`, changing it to `<I * 2>` solves compiler crash. i know that it doesn't solve the problem, but maybe this information will help you to figure out why this error occurs. if no - never mind, i can bind function using std::function.

**Comment by ThePhD** [comment]
I still can't repro, no matter what settings. =/ Maybe if anyone else is within earshot of this, they can repro too?

**Comment by eliasdaler** [comment]
I use VS 2015 Update 3. The code works on Debug, but gives me the same error on release.
[Here are my settings](https://www.dropbox.com/s/5xhu2gkxklr6794/Exported-2016-07-24.vssettings?dl=0) (I just exported most of the stuff, so be sure to back up your settings before testing!)

**Comment by ThePhD** [comment]
Fooound it.

So, I have to be building for x86. x64 builds don't suffer the same problem on Release.

Ostensibly, I'm really not sure how to get around this extremely specific ICE. I'll have to figure out something very clever?

**Comment by ThePhD** [comment]
Fun fact: it needs to be _exactly_ 4 floats on x86 with Release parameters. 3 floats + and int is fine, 5 floats is fine... I'm willing to be this has to do with codegeneration in newer VSes which try to insert SSE instructions to manipulate 4 floats at a time.

That's kind've jank of them, to break something like this.

I have no possible idea how I'd fix this more properly. I'm hitting some odd corner case and there's no information out there on how to fix it. =/

**Comment by ThePhD** [comment]
Preliminary suggestion is to just return a `double`. If this data is going to go into Lua, then a `double` is what gets stored anyways. If this data is going through Lua to C++, well, it will be stored in Lua as a `double`, and then be retrieved in C++ as a float.

I'm sorry it's like this, but there's legit nothing I can do. I'm going to have to create a SSCCE to take to the VC++ Compiler devs and ask them WTF they're doing and if they can fix it soon.

I'm closing as "Can't do anything about this" right now. I'm sorry if the answer is unsatisfying.

**Comment by kiwidoggie** [comment]
@ThePhD Have you created a thread on visual studio connect for this issue?

**Comment by ThePhD** [comment]
@kiwidoggie No, because I can't even.

I'm in school, I have stuff to do, this is one of like 4 compiler bugs I'd need to SSCCE and compile. My language proposal is due today and crap. I don't have _time_ to deal with this. Someone else will have to. =/

**Comment by kiwidoggie** [comment]
I will, thank you. I understand how busy you are. I created an issue on the MSFT Connect tracker.

**Comment by IronsDu** [comment]
Hi, My VS is :
Microsoft Visual Studio Community 2015
14.0.23107.0 D14REL.
Compiler tutorial , cause error. excuse me,  which vs version is correct ? thank you.

**Comment by ThePhD** [comment]
@IronsDu "Compiler tutorial" ? Which one, the one on the `Getting Started` page? Please provide some code, or open up a new issue on Github Issues here: https://github.com/ThePhD/sol2/issues

**Comment by IronsDu** [comment]
@ThePhD I want use sol2 in my [Joynet](https://github.com/IronsDu/Joynet/blob/master/src/Joynet.cpp#L572), but cause error https://github.com/ThePhD/sol2/issues/154, so, i cut [http://sol2.readthedocs.io/en/latest/tutorial/cxx-in-lua.html#player-script-cpp](http://sol2.readthedocs.io/en/latest/tutorial/cxx-in-lua.html#player-script-cpp,)  in luaopen_Joynet function for test, but cause the same error.

**Comment by ThePhD** [comment]
@IronsDu Upgrade to the latest Visual Studio 2015: the version you're using is not the latest.

**Comment by gigiyq** [comment]
Hi,
Do you resolve it?
I encountered the similar problem, and my vs version is 14.0.25431.01 Update 3.

**Comment by ThePhD** [comment]
@gigiyq @IronsDu See issue #269 where I will attempt to figure out what is wrong and solve it. When I copy-paste code from the tutorial and run it, it works. The code in the documentation is also ran as part of our travis-ci tests, and if it does not compile or run successfully our tests fail.

**Comment by justinchen00** [comment]
can't build my program with VS2015 UPDATE 3

*.cpp : fatal error C1001: An internal error has occurred in the compiler.
6>  (compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 255)
6>   To work around this problem, try simplifying or changing the program near the locations listed above.
6>  Please choose the Technical Support command on the Visual C++
6>   Help menu, or open the Technical Support help file for more information
6>    link!InvokeCompilerPass()+0x297b2
6>    link!InvokeCompilerPass()+0x297b2
6>    link!InvokeCompilerPass()+0x28b04
6>    link!DllGetC2Telemetry()+0xe3113
6>    link!CloseTypeServerPDB()+0x14fd
6>
6>
6>LINK : fatal error LNK1000: Internal error during IMAGE::BuildImage
6>
6>    Version 14.00.24215.1
6>
6>    ExceptionCode            = C0000005
6>    ExceptionFlags           = 00000000
6>    ExceptionAddress         = 5076DD48 (503C0000) "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\c2.dll"
6>    NumberParameters         = 00000002
6>    ExceptionInformation[ 0] = 00000000
6>    ExceptionInformation[ 1] = 00000024
6>
6>  CONTEXT:
6>    Eax    = 00000000  Esp    = 0036E940
6>    Ebx    = 0000007C  Ebp    = 0036E950
6>    Ecx    = 00002FDE  Esi    = 2C39B0AE
6>    Edx    = 00000000  Edi    = 04F4002C
6>    Eip    = 5076DD48  EFlags = 00010216
6>    SegCs  = 00000023  SegDs  = 0000002B
6>    SegSs  = 0000002B  SegEs  = 0000002B
6>    SegFs  = 00000053  SegGs  = 0000002B
6>    Dr0    = 00000000  Dr3    = 00000000
6>    Dr1    = 00000000  Dr6    = 00000000
6>    Dr2    = 00000000  Dr7    = 00000000
========== Build: 5 succeeded, 1 failed, 7 up-to-date, 0 skipped ==========

**Comment by isuruf** [comment]
FYI, here's a workaround to this ICE https://gist.github.com/isuruf/449b9db908834683a7255e9bbb749ebb
